<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All Product' => 'Barcha masulot',
    'Amount' => 'Barcha miqdori',
    'Amount of income' => 'Daromad miqdori',
    'Are you sure you want to delete this item?' => 'Haqiqatan ham ushbu elementni o\'chirishni xohlaysizmi',
    'Create' => 'Qo\'shish',
    'Create Product' => 'Maxsulot qo\'shish',
    'Create Product Document' => 'Maxsulot uchun Hujjat yaratish',
    'Created At' => 'Yaratilgan vaqt',
    'Created By' => 'Kim tomonidan yaratildi',
    'Date' => 'Vaqt',
    'Delete' => 'O\'chirish',
    'Doc Number' => 'Hujjat raqami',
    'Doc Type' => 'Hujjat tipi',
    'Document Number' => 'Hujjat raqami',
    'End Date' => 'Yakunlash sanasi',
    'ID' => 'Id',
    'Incoming Price' => 'Keladigan summasi',
    'Name' => 'Nom',
    'Party Number' => 'Partiya raqam',
    'Password' => 'Parol',
    'Product Doc ID' => 'Maxsulot Hujjat Id',
    'Product Doc Items ID' => 'Maxsulot hujjat shakli',
    'Product Documents' => 'Maxsulot hujjatlari',
    'Product ID' => 'Maxsulot id',
    'Product name' => 'Maxsulot nomi',
    'Products' => 'Maxsulotlar',
    'Quantity' => 'Miqdori',
    'Report' => 'Hisobot',
    'Reset' => 'Yangilash',
    'Save' => 'Saqlash',
    'Save And Finish' => 'Saqlash va tugatish',
    'Search' => 'Qidiruv',
    'Start Date' => 'Boshlanish sanasi',
    'Status' => 'Holati',
    'The requested page does not exist.' => 'So\'ralgan sahifa mavjud emas.',
    'The total amount of income' => 'Kirim to\'liq miqdori',
    'Update' => 'Yangilash',
    'Update Product Document: {name}' => 'Maxsulot hujjatini yangilash {name}',
    'Update Product: {name}' => 'Maxsulotni yangilash {name}',
    'Updated At' => 'Yangilash vaqti',
    'Updated By' => 'Kim tomonidan yangilandi',
    'Username' => 'Foydalanuvchi login',
    'All' => 'Jami',
    'Error! No such product was found in the warehouse' => 'Xato! Omborda bunday mahsulot topilmadi',
    'Incoming price' => 'Kelishi summasi',
    'No Saved' => 'Saqlanmadi',
    'No Updated' => 'Yangilanmadi',
    'No updated' => 'Yangilanmadi',
    'Not Found' => 'Topilmadi',
    'Profit' => 'Foyda',
    'Qty Difference' => 'Sotilgan miqdor',
    'Quantity Difference' => 'Sotilgan miqdor',
    'Selling Price' => 'Sotilgan narx',
    'Selling price' => 'Sotilgan narxi',
    'date' => 'Qaysi vaqt',
];
