<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Amount' => 'Barcha miqdori',
    'Are you sure you want to delete this item?' => 'Haqiqatan ham ushbu elementni o\'chirishni xohlaysizmi',
    'Create' => 'Qo\'shish',
    'Create Product' => 'Maxsulot qo\'shish',
    'Create Product Document' => 'Maxsulot uchun Hujjat yaratish',
    'Created At' => 'Yaratilgan vaqt',
    'Created By' => 'Kim tomonidan yaratildi',
    'Date' => 'Vaqt',
    'Delete' => 'O\'chirish',
    'Doc Number' => 'Hujjat raqami',
    'Doc Type' => 'Hujjat tipi',
    'ID' => 'Id',
    'Incoming Price' => 'Keladigan summasi',
    'Large quantities of products were introduced.' => 'Ko\'p miqdorda mahsulotlar kiritildi.',
    'Name' => 'Nom',
    'No product found' => 'Maxsulot aniqlanmadi',
    'Partiy Number' => 'Partiya raqam',
    'Party Number' => 'Partiya raqam',
    'Password' => 'Parol',
    'Product Doc ID' => 'Maxsulot Hujjat Id',
    'Product Doc Items ID' => 'Maxsulot hujjat shakli',
    'Product Documents' => 'Maxsulot hujjatlari',
    'Product ID' => 'Maxsulot id',
    'Products' => 'Maxsulotlar',
    'Quantity' => 'Miqdori',
    'Reset' => 'Yangilash',
    'Save' => 'Saqlash',
    'Save And Finish' => 'Saqlash va tugatish',
    'Save and finish failed' => 'Saqlash va tugatilish bajarilmadi',
    'Search' => 'Qidiruv',
    'Status' => 'Holati',
    'The requested page does not exist.' => 'So\'ralgan sahifa mavjud emas.',
    'Update' => 'Yangilash',
    'Update Product Document: {name}' => 'Maxsulot hujjatini yangilash {name}',
    'Update Product: {name}' => 'Maxsulotni yangilash {name}',
    'Updated At' => 'Yangilash vaqti',
    'Updated By' => 'Kim tomonidan yangilandi',
    'Username' => 'Foydalanuvchi login',
    'Amount of income' => 'Daromad miqdori',
    'Available' => 'Qolgan maxsulot miqdori',
    'Document Number' => 'Hujjat raqami',
    'Product name' => 'Maxsulot nomi',
    'Report' => 'Hisobot',
    'Sold' => 'Sotildi',
    'Start Date' => 'Boshlanish sanasi',
    'End Date' => 'Yakunlash sanasi',
    'The total amount of income' => "Kirim to'liq miqdori",
    'All Product' => 'Barcha masulot'
];
